main: ic.Ikrlegido12.IkrCore
version: beta-0.4
name: IkrCore
author: Ikrlegido12
description: Un plugin programado por Ikrlegido12.
api-version: 1.16
commands:
  ikrcore:
    description: Comando principal.
    aliases:
      - ikrlegidoplugin
      - iamverycool
      - ic
  volar:
    description: Comando para volar
    aliases:
      - fly
  experiencia:
    description: Comando de XP.

    # spawn:
   # description: Te teletransporta al spawn.
  #  aliases:
 #     - hub
